# version: '3.8'

services:
  web:    
    image: newsapp:${TAG}
    container_name: news_web
    restart: always
    
    # 개발중에만 사용 / 배포용으로는 주석처리
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"    
    networks:
      - mynetwork
    env_file:
      - .env.prod  
    volumes:
      - static_volume:/app/staticfiles  # 공유 static
      - ./get_news:/app/get_news        # 크롤링 코드 공유
      - ./.env.prod:/app/.env.prod  # ✅ 이 줄 추가!

  nginx:
    image: nginx:latest
    container_name: news_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles  # 공유 static
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:  
  static_volume:  # ✅ Django와 nginx가 공유하는 볼륨  