name: Deploy to Lightsail

on:
  push:
    branches: [ "main" ]

env:
  LIGHTSAIL_INSTANCE_NAME: "WebStack01"
  AWS_REGION: "ap-northeast-2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and tag Docker image
        working-directory: ./newsapp
        run: |
          docker build -t newsapp:${{ github.sha }} .
          docker save newsapp:${{ github.sha }} > newsapp.tar
          mv newsapp.tar $GITHUB_WORKSPACE/

      - name: Install AWS CLI and Lightsail Plugin
        run: |
          echo "Checking AWS CLI version..."
          aws --version || echo "AWS CLI not found, installing..."
          
          echo "Downloading AWS CLI..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          
          echo "Installing or updating AWS CLI..."
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          
          echo "Verifying AWS CLI installation..."
          aws --version
          aws lightsail get-instance --instance-name ${{ env.LIGHTSAIL_INSTANCE_NAME }}

      - name: Copy Docker image to Lightsail
        run: |
          aws lightsail get-instance-access-details --instance-name ${{ env.LIGHTSAIL_INSTANCE_NAME }} > instance_details.json
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem
          
          INSTANCE_IP=$(jq -r '.accessDetails.ipAddress' instance_details.json)
          scp -o StrictHostKeyChecking=no -i lightsail_key.pem newsapp.tar ubuntu@$INSTANCE_IP:~/

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            # 도커 이미지 로드
            docker load < newsapp.tar
            
            # 기존 컨테이너 중지 및 제거
            docker-compose -f docker-compose.prod.yml down || true
            
            # 환경 변수 파일 생성
            echo "DB_NAME=${{ secrets.DB_NAME }}" > .env.prod
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env.prod
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.prod
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.prod
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.prod
            
            # docker-compose 파일 생성
            cat > docker-compose.prod.yml << 'EOL'
            version: '3.8'
            services:
              web:
                image: newsapp:${{ github.sha }}
                ports:
                  - "8000:8000"
                env_file:
                  - .env.prod
                restart: always
            networks:
              default:
                name: newsapp-network
            EOL
            
            # 새 컨테이너 시작
            docker-compose -f docker-compose.prod.yml up -d
            
            # 사용하지 않는 이미지 정리
            docker image prune -af 